--14  Lines
INSERT INTO master_data (issuer_name, issue_symbol, "location", start_nyse, start_nyse_arca, start_nyse_american, start_nasdaq, start_nasdaq_global_select_market, start_nasdaq_select_market, start_nasdaq_capital_market, is_company, category, renamed_to_issuer_name, renamed_to_issue_symbol, renamed_at_date, current_name, suspended, suspension_date, start_cboe) VALUES
('MAIDEN HOLDINGS LTD 6.625% NTS 14/06/46 USD25', 'MHLA', 'USA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('ETRACS 2X LEVERAGED MSCI US MOMENTUM FACTOR TR ETN', 'MTUL', 'USA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('GENIUS GROUP LTD', 'GNS', 'USA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('YANDEX N.V.', 'YNDX', 'USA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('NEXT E GO N V', 'EGOX', 'USA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('KAROOOOO LTD', 'KARO', 'USA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('KAROOOOO LTD2', 'KARO2', 'USA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('ISHARES INC', '$ESGE.IV', 'USA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('GOLDMAN SACHS PHYSICAL GOLD ETF SHARES', 'AAAU', 'USA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('S&P 100 INDEX', '$OEX', 'USA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('S&P 101 INDEX', 'ABC1', 'USA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('S&P 102 INDEX', 'ABC2', 'USA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('S&P 103 INDEX', 'ABCD', 'USA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('IGZ (LISTING MARKET NYSE ARCA NETWORK B F)', 'IGZ', 'USA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('TEST Company', 'ABC', 'USA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);