INSERT INTO nyse_instruments (instrument_name, instrument_type, symbol_ticker, symbol_exchange_ticker, normalized_ticker, symbol_esignal_ticker, mic_code, dateloaded, is_staged) VALUES
('MAIDEN HOLDINGS LTD 6.625% NTS 14/06/46 USD25', 'PREFERRED_STOCK', 'MHLA', 'MHLA', 'MHLA', 'MHLA', 'XNYS', '2024-01-11', false),
('ETRACS 2X LEVERAGED MSCI US MOMENTUM FACTOR TR ETN', 'EXCHANGE_TRADED_NOTE', 'MTUL', 'MTUL', 'MTUL', 'MTUL', 'ARCX', '2024-01-11', false),
('GENIUS GROUP LTD', 'NOTE', 'GNS', 'GNS', 'GNS', 'GNS', 'XASE', '2024-01-11', false),
('YANDEX N.V.', 'RIGHT', 'YNDX', 'YNDX', 'YNDX', 'YNDX', 'XNGS', '2024-01-11', false),
('NEXT E GO N V', 'TRUST', 'EGOX', 'EGOX', 'EGOX', 'EGOX', 'XNMS', '2024-01-11', false),
('KAROOOOO LTD', 'COMMON_STOCK', 'KARO', 'KARO', 'KARO', 'KARO', 'XNCM', '2024-01-11', false),
('ISHARES INC', 'EXCHANGE_TRADED_FUND', 'E:ESGE', 'ESGE', 'ESGE', '$ESGE.IV', 'XNAS', '2024-01-11', false),
('GOLDMAN SACHS PHYSICAL GOLD ETF SHARES', 'EXCHANGE_TRADED_FUND', 'AAAU', 'AAAU', 'AAAU', 'AAAU', 'BATS', '2024-01-11', false),
('S&P 100 INDEX', 'INDEX', 'I:OEX', 'OEX', 'OEX', '$OEX', 'XCBO', '2024-01-11', false),
('S&P 101 INDEX', 'EQUITY', 'ABC1', 'ABC1', 'ABC1', 'ABC1', 'BATY', '2024-01-11', false),
('S&P 102 INDEX', 'REIT', 'ABC2', 'ABC2', 'ABC2', 'ABC2', 'EDGA', '2024-01-11', false),
('S&P 103 INDEX', 'UNIT', 'ABCD', 'ABCD', 'ABCD', 'ABCD', 'EDGX', '2024-01-11', false),
('IGZ (LISTING MARKET NYSE ARCA NETWORK B F)', 'TEST', 'IGZ', 'IGZ', 'IGZ', 'IGZ', 'ARCX', '2024-01-11', false),
('BANK OF HAWAII CORPORATION', 'COMMON_STOCK', 'BOH', 'BOH', 'BOH', 'BOH', 'XNYS', '2024-01-11', false),
('AURORA TECHNOLOGY ACQUISITION CORP COM USD0.0001(27/01/2027 SUB/RIGHTS)', 'RIGHT', 'ATAKR', 'ATAKR', 'ATAKR', 'ATAKR', 'XNMS', '2024-01-11', false);