[package]
name = "cicd-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib] # lib
path = "src/lib.rs"

[[bin]]
name = "data-collector"
path = "src/main.rs"


[dependencies]


[dev-dependencies]
