-- noinspection SqlNoDataSourceInspectionForFile

-- Add migration script here
CREATE TABLE MIC_CODES (
    Market_Name VARCHAR(255) NOT NULL,
    Mic_Code CHAR(4) NOT NULL,
    PRIMARY KEY (Mic_Code)
);
INSERT INTO MIC_CODES (Mic_Code, Market_Name) VALUES
('ARCX', 'NYSE ARCA'),
('BATS', 'CBOE BZX U.S. EQUITIES EXCHANGE'),
('IEXG', 'INVESTORS EXCHANGE - DAX FACILITY'),
('XASE', 'NYSE MKT LLC'),
('XCBO', 'CBOE GLOBAL MARKETS INC.'),
('XCME', 'CHICAGO MERCANTILE EXCHANGE'),
('XNAS', 'NASDAQ - ALL MARKETS'),
('XNCM', 'NASDAQ CAPITAL MARKET'),
('XNGS', 'NASDAQ/NGS (GLOBAL SELECT MARKET)'),
('XNMS', 'NASDAQ/NMS (GLOBAL MARKET)'),
('XNYS', 'NEW YORK STOCK EXCHANGE, INC.'),
('XSTX', 'STOXX LIMITED - INDICES'),
('XXXX', 'NO MARKET');

