-- noinspection SqlNoDataSourceInspectionForFile

-- Add migration script here
CREATE TABLE COUNTRIES (
       Country_code CHAR(3) NOT NULL,
       Nation VARCHAR(100) NOT NULL DEFAULT '',
       Federal_state VARCHAR(100) NOT NULL DEFAULT '',
       SEC_code VARCHAR(10),
       PRIMARY KEY (Country_code, Nation, Federal_state)
);

--Insert country data (expect USA and Canada)
INSERT INTO countries (Country_code, Nation, SEC_code)
VALUES
    ('AFG', 'AFGHANISTAN', 'B2'),
    ('ALA', 'ALAND ISLANDS', 'Y6'),
    ('ALB', 'ALBANIA', 'B3'),
    ('DZA', 'ALGERIA', 'B4'),
    ('ASM', 'AMERICAN SAMOA', 'B5'),
    ('AND', 'ANDORRA', 'B6'),
    ('AGO', 'ANGOLA', 'B7'),
    ('AIA', 'ANGUILLA', '1A'),
    ('ATA', 'ANTARCTICA', 'B8'),
    ('ATG', 'ANTIGUA AND BARBUDA', 'B9'),
    ('ARG', 'ARGENTINA', 'C1'),
    ('ARM', 'ARMENIA', '1B'),
    ('ABW', 'ARUBA', '1C'),
    ('AUS', 'AUSTRALIA', 'C3'),
    ('AUT', 'AUSTRIA', 'C4'),
    ('AZE', 'AZERBAIJAN', '1D'),
    ('BHS', 'BAHAMAS', 'C5'),
    ('BHR', 'BAHRAIN', 'C6'),
    ('BGD', 'BANGLADESH', 'C7'),
    ('BRB', 'BARBADOS', 'C8'),
    ('BLR', 'BELARUS', '1F'),
    ('BEL', 'BELGIUM', 'C9'),
    ('BLZ', 'BELIZE', 'D1'),
    ('BEN', 'BENIN', 'G6'),
    ('BMU', 'BERMUDA', 'D0'),
    ('BTN', 'BHUTAN', 'D2'),
    ('BOL', 'BOLIVIA', 'D3'),
    ('BIH', 'BOSNIA AND HERZEGOVINA', '1E'),
    ('BWA', 'BOTSWANA', 'B1'),
    ('BVT', 'BOUVET ISLAND', 'D4'),
    ('BRA', 'BRAZIL', 'D5'),
    ('IOT', 'BRITISH INDIAN OCEAN TERRITORY', 'D6'),
    ('BRN', 'BRUNEI DARUSSALAM', 'D9'),
    ('BGR', 'BULGARIA', 'E0'),
    ('BFA', 'BURKINA FASO', 'X2'),
    ('BDI', 'BURUNDI', 'E2'),
    ('KHM', 'CAMBODIA', 'E3'),
    ('CMR', 'CAMEROON', 'E4'),
    ('CAN', 'CANADA (Federal Level)', 'Z4'),
    ('CPV', 'CAPE VERDE', 'E8'),
    ('CYM', 'CAYMAN ISLANDS', 'E9'),
    ('CAF', 'CENTRAL AFRICAN REPUBLIC', 'F0'),
    ('TCD', 'CHAD', 'F2'),
    ('CHL', 'CHILE', 'F3'),
    ('CHN', 'CHINA', 'F4'),
    ('CXR', 'CHRISTMAS ISLAND', 'F6'),
    ('CCK', 'COCOS (KEELING) ISLANDS', 'F7'),
    ('COL', 'COLOMBIA', 'F8'),
    ('COM', 'COMOROS', 'F9'),
    ('COG', 'CONGO', 'G0'),
    ('COD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'Y3'),
    ('COK', 'COOK ISLANDS', 'G1'),
    ('CRI', 'COSTA RICA', 'G2'),
    ('CIV', 'COTE DIVOIRE', 'L7'),
    ('HRV', 'CROATIA', '1M'),
    ('CUB', 'CUBA', 'G3'),
    ('CYP', 'CYPRUS', 'G4'),
    ('CZE', 'CZECH REPUBLIC', '2N'),
    ('DNK', 'DENMARK', 'G7'),
    ('DJI', 'DJIBOUTI', '1G'),
    ('DMA', 'DOMINICA', 'G9'),
    ('DOM', 'DOMINICAN REPUBLIC', 'G8'),
    ('ECU', 'ECUADOR', 'H1'),
    ('EGY', 'EGYPT', 'H2'),
    ('SLV', 'EL SALVADOR', 'H3'),
    ('GNQ', 'EQUATORIAL GUINEA', 'H4'),
    ('ERI', 'ERITREA', '1J'),
    ('EST', 'ESTONIA', '1H'),
    ('ETH', 'ETHIOPIA', 'H5'),
    ('FLK', 'FALKLAND ISLANDS (MALVINAS)', 'H7'),
    ('FRO', 'FAROE ISLANDS', 'H6'),
    ('FJI', 'FIJI', 'H8'),
    ('FIN', 'FINLAND', 'H9'),
    ('FRA', 'FRANCE', 'I0'),
    ('GUF', 'FRENCH GUIANA', 'I3'),
    ('PYF', 'FRENCH POLYNESIA', 'I4'),
    ('ATF', 'FRENCH SOUTHERN TERRITORIES', '2C'),
    ('GAB', 'GABON', 'I5'),
    ('GMB', 'GAMBIA', 'I6'),
    ('GEO', 'GEORGIA', '2Q'),
    ('DEU', 'GERMANY', '2M'),
    ('GHA', 'GHANA', 'J0'),
    ('GIB', 'GIBRALTAR', 'J1'),
    ('GRC', 'GREECE', 'J3'),
    ('GRL', 'GREENLAND', 'J4'),
    ('GRD', 'GRENADA', 'J5'),
    ('GLP', 'GUADELOUPE', 'J6'),
    ('GUM', 'GUAM', 'GU'),
    ('GTM', 'GUATEMALA', 'J8'),
    ('GGY', 'GUERNSEY', 'Y7'),
    ('GIN', 'GUINEA', 'J9'),
    ('GNB', 'GUINEA-BISSAU', 'S0'),
    ('GUY', 'GUYANA', 'K0'),
    ('HTI', 'HAITI', 'K1'),
    ('HMD', 'HEARD ISLAND AND MCDONALD ISLANDS', 'K4'),
    ('X4', 'HOLY SEE (VATICAN CITY STATE)', 'X4'),
    ('HND', 'HONDURAS', 'K2'),
    ('HKG', 'HONG KONG', 'K3'),
    ('HUN', 'HUNGARY', 'K5'),
    ('ISL', 'ICELAND', 'K6'),
    ('IND', 'INDIA', 'K7'),
    ('IDN', 'INDONESIA', 'K8'),
    ('IRN', 'IRAN, ISLAMIC REPUBLIC OF', 'K9'),
    ('IRQ', 'IRAQ', 'L0'),
    ('IRL', 'IRELAND', 'L2'),
    ('IMN', 'ISLE OF MAN', 'Y8'),
    ('ISR', 'ISRAEL', 'L3'),
    ('ITA', 'ITALY', 'L6'),
    ('JAM', 'JAMAICA', 'L8'),
    ('JPN', 'JAPAN', 'M0'),
    ('JEY', 'JERSEY', 'Y9'),
    ('JOR', 'JORDAN', 'M2'),
    ('KAZ', 'KAZAKHSTAN', '1P'),
    ('KEN', 'KENYA', 'M3'),
    ('KIR', 'KIRIBATI', 'J2'),
    ('PRK', 'KOREA, DEMOCRATIC PEOPLES REPUBLIC OF', 'M4'),
    ('KOR', 'KOREA, REPUBLIC OF', 'M5'),
    ('KWT', 'KUWAIT', 'M6'),
    ('KGZ', 'KYRGYZSTAN', '1N'),
    ('LAO', 'LAO PEOPLES DEMOCRATIC REPUBLIC', 'M7'),
    ('LVA', 'LATVIA', '1R'),
    ('LBN', 'LEBANON', 'M8'),
    ('LSO', 'LESOTHO', 'M9'),
    ('LBR', 'LIBERIA', 'N0'),
    ('LBY', 'LIBYAN ARAB JAMAHIRIYA', 'N1'),
    ('LIE', 'LIECHTENSTEIN', 'N2'),
    ('LTU', 'LITHUANIA', '1Q'),
    ('LUX', 'LUXEMBOURG', 'N4'),
    ('MAC', 'MACAU', 'N5'),
    ('MKD', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', '1U'),
    ('MDG', 'MADAGASCAR', 'N6'),
    ('MWI', 'MALAWI', 'N7'),
    ('MYS', 'MALAYSIA', 'N8'),
    ('MDV', 'MALDIVES', 'N9'),
    ('MLI', 'MALI', 'O0'),
    ('MLT', 'MALTA', 'O1'),
    ('MHL', 'MARSHALL ISLANDS', '1T'),
    ('MTQ', 'MARTINIQUE', 'O2'),
    ('MRT', 'MAURITANIA', 'O3'),
    ('MUS', 'MAURITIUS', 'O4'),
    ('MYT', 'MAYOTTE', '2P'),
    ('MEX', 'MEXICO', 'O5'),
    ('FSM', 'MICRONESIA, FEDERATED STATES OF', '1K'),
    ('MDA', 'MOLDOVA, REPUBLIC OF', '1S'),
    ('MCO', 'MONACO', 'O9'),
    ('MNG', 'MONGOLIA', 'P0'),
    ('MNE', 'MONTENEGRO', 'Z5'),
    ('MSR', 'MONTSERRAT', 'P1'),
    ('MAR', 'MOROCCO', 'P2'),
    ('MOZ', 'MOZAMBIQUE', 'P3'),
    ('MMR', 'MYANMAR', 'E1'),
    ('NAM', 'NAMIBIA', 'T6'),
    ('NRU', 'NAURU', 'P5'),
    ('NPL', 'NEPAL', 'P6'),
    ('NLD', 'NETHERLANDS', 'P7'),
    ('ANT', 'NETHERLANDS ANTILLES', 'P8'),
    ('NCL', 'NEW CALEDONIA', '1W'),
    ('NZL', 'NEW ZEALAND', 'Q2'),
    ('NIC', 'NICARAGUA', 'Q3'),
    ('NER', 'NIGER', 'Q4'),
    ('NGA', 'NIGERIA', 'Q5'),
    ('NIU', 'NIUE', 'Q6'),
    ('NFK', 'NORFOLK ISLAND', 'Q7'),
    ('MNP', 'NORTHERN MARIANA ISLANDS', '1V'),
    ('NOR', 'NORWAY', 'Q8'),
    ('OMN', 'OMAN', 'P4'),
    ('PAK', 'PAKISTAN', 'R0'),
    ('PLW', 'PALAU', '1Y'),
    ('PSE', 'PALESTINIAN TERRITORY, OCCUPIED', '1X'),
    ('PAN', 'PANAMA', 'R1'),
    ('PNG', 'PAPUA NEW GUINEA', 'R2'),
    ('PRY', 'PARAGUAY', 'R4'),
    ('PER', 'PERU', 'R5'),
    ('PHL', 'PHILIPPINES', 'R6'),
    ('PCN', 'PITCAIRN', 'R8'),
    ('POL', 'POLAND', 'R9'),
    ('PRT', 'PORTUGAL', 'S1'),
    ('PRI', 'PUERTO RICO', 'PR'),
    ('QAT', 'QATAR', 'S3'),
    ('REU', 'REUNION', 'S4'),
    ('ROU', 'ROMANIA', 'S5'),
    ('RUS', 'RUSSIAN FEDERATION', '1Z'),
    ('BLM', 'SAINT BARTHELEMY', 'Z0'),
    ('SHN', 'SAINT HELENA', 'U8'),
    ('KNA', 'SAINT KITTS AND NEVIS', 'U7'),
    ('LCA', 'SAINT LUCIA', 'U9'),
    ('MAF', 'SAINT MARTIN', 'Z1'),
    ('SPM', 'SAINT PIERRE AND MIQUELON', 'V0'),
    ('VCT', 'SAINT VINCENT AND THE GRENADINES', 'V1'),
    ('WSM', 'SAMOA', 'Y0'),
    ('SMR', 'SAN MARINO', 'S8'),
    ('STP', 'SAO TOME AND PRINCIPE', 'S9'),
    ('SRB', 'SERBIA', 'Z2'),
    ('SYC', 'SEYCHELLES', 'T2'),
    ('RWA', 'RWANDA', 'S6'),
    ('SAU', 'SAUDI ARABIA', 'T0'),
    ('SEN', 'SENEGAL', 'T1'),
    ('SLE', 'SIERRA LEONE', 'T8'),
    ('SGP', 'SINGAPORE', 'U0'),
    ('SVK', 'SLOVAKIA', '2B'),
    ('SVN', 'SLOVENIA', '2A'),
    ('SLB', 'SOLOMON ISLANDS', 'D7'),
    ('SOM', 'SOMALIA', 'U1'),
    ('ZAF', 'SOUTH AFRICA', 'T3'),
    ('SGS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', '1L'),
    ('ESP', 'SPAIN', 'U3'),
    ('LKA', 'SRI LANKA', 'F1'),
    ('SDN', 'SUDAN', 'V2'),
    ('SUR', 'SURINAME', 'V3'),
    ('SJM', 'SVALBARD AND JAN MAYEN', 'L9'),
    ('SWZ', 'SWAZILAND', 'V6'),
    ('SWE', 'SWEDEN', 'V7'),
    ('CHE', 'SWITZERLAND', 'V8'),
    ('SYR', 'SYRIAN ARAB REPUBLIC', 'V9'),
    ('TWN', 'TAIWAN', 'F5'),
    ('TJK', 'TAJIKISTAN', '2D'),
    ('TZA', 'TANZANIA, UNITED REPUBLIC OF', 'W0'),
    ('THA', 'THAILAND', 'W1'),
    ('TLS', 'TIMOR-LESTE', 'Z3'),
    ('TGO', 'TOGO', 'W2'),
    ('TKL', 'TOKELAU', 'W3'),
    ('TON', 'TONGA', 'W4'),
    ('TTO', 'TRINIDAD AND TOBAGO', 'W5'),
    ('TUN', 'TUNISIA', 'W6'),
    ('TUR', 'TURKEY', 'W8'),
    ('TKM', 'TURKMENISTAN', '2E'),
    ('TCA', 'TURKS AND CAICOS ISLANDS', 'W7'),
    ('TUV', 'TUVALU', '2G'),
    ('UGA', 'UGANDA', 'W9'),
    ('UKR', 'UKRAINE', '2H'),
    ('ARE', 'UNITED ARAB EMIRATES', 'C0'),
    ('GBR', 'UNITED KINGDOM', 'X0'),
    ('UMI', 'UNITED STATES MINOR OUTLYING ISLANDS', '2J'),
    ('URY', 'URUGUAY', 'X3'),
    ('UZB', 'UZBEKISTAN', '2K'),
    ('VUT', 'VANUATU', '2L'),
    ('VEN', 'VENEZUELA', 'X5'),
    ('VNM', 'VIET NAM', 'Q1'),
    ('VGB', 'VIRGIN ISLANDS, BRITISH', 'D8'),
    ('VIR', 'VIRGIN ISLANDS, U.S.', 'VI'),
    ('WLF', 'WALLIS AND FUTUNA', 'X8'),
    ('ESH', 'WESTERN SAHARA', 'U5'),
    ('YEM', 'YEMEN', 'T7'),
    ('ZMB', 'ZAMBIA', 'Y4'),
    ('ZWE', 'ZIMBABWE', 'Y5'),
    ('XXX', 'UNKNOWN', 'XX');

--Insert USA data
INSERT INTO countries (Country_code, Nation, Federal_state, SEC_code)
VALUES
    ('USA', 'United States of America', 'ALABAMA', 'AL'),
    ('USA', 'United States of America', 'ALASKA', 'AK'),
    ('USA', 'United States of America', 'ARIZONA', 'AZ'),
    ('USA', 'United States of America', 'ARKANSAS', 'AR'),
    ('USA', 'United States of America', 'CALIFORNIA', 'CA'),
    ('USA', 'United States of America', 'COLORADO', 'CO'),
    ('USA', 'United States of America', 'CONNECTICUT', 'CT'),
    ('USA', 'United States of America', 'DELAWARE', 'DE'),
    ('USA', 'United States of America', 'DISTRICT OF COLUMBIA', 'DC'),
    ('USA', 'United States of America', 'FLORIDA', 'FL'),
    ('USA', 'United States of America', 'GEORGIA', 'GA'),
    ('USA', 'United States of America', 'HAWAII', 'HI'),
    ('USA', 'United States of America', 'IDAHO', 'ID'),
    ('USA', 'United States of America', 'ILLINOIS', 'IL'),
    ('USA', 'United States of America', 'INDIANA', 'IN'),
    ('USA', 'United States of America', 'IOWA', 'IA'),
    ('USA', 'United States of America', 'KANSAS', 'KS'),
    ('USA', 'United States of America', 'KENTUCKY', 'KY'),
    ('USA', 'United States of America', 'LOUISIANA', 'LA'),
    ('USA', 'United States of America', 'MAINE', 'ME'),
    ('USA', 'United States of America', 'MARYLAND', 'MD'),
    ('USA', 'United States of America', 'MASSACHUSETTS', 'MA'),
    ('USA', 'United States of America', 'MICHIGAN', 'MI'),
    ('USA', 'United States of America', 'MINNESOTA', 'MN'),
    ('USA', 'United States of America', 'MISSISSIPPI', 'MS'),
    ('USA', 'United States of America', 'MISSOURI', 'MO'),
    ('USA', 'United States of America', 'MONTANA', 'MT'),
    ('USA', 'United States of America', 'NEBRASKA', 'NE'),
    ('USA', 'United States of America', 'NEVADA', 'NV'),
    ('USA', 'United States of America', 'NEW HAMPSHIRE', 'NH'),
    ('USA', 'United States of America', 'NEW JERSEY', 'NJ'),
    ('USA', 'United States of America', 'NEW MEXICO', 'NM'),
    ('USA', 'United States of America', 'NEW YORK', 'NY'),
    ('USA', 'United States of America', 'NORTH CAROLINA', 'NC'),
    ('USA', 'United States of America', 'NORTH DAKOTA', 'ND'),
    ('USA', 'United States of America', 'OHIO', 'OH'),
    ('USA', 'United States of America', 'OKLAHOMA', 'OK'),
    ('USA', 'United States of America', 'OREGON', 'OR'),
    ('USA', 'United States of America', 'PENNSYLVANIA', 'PA'),
    ('USA', 'United States of America', 'RHODE ISLAND', 'RI'),
    ('USA', 'United States of America', 'SOUTH CAROLINA', 'SC'),
    ('USA', 'United States of America', 'SOUTH DAKOTA', 'SD'),
    ('USA', 'United States of America', 'TENNESSEE', 'TN'),
    ('USA', 'United States of America', 'TEXAS', 'TX'),
    ('USA', 'United States of America', 'UNITED STATES', 'X1'),
    ('USA', 'United States of America', 'UTAH', 'UT'),
    ('USA', 'United States of America', 'VERMONT', 'VT'),
    ('USA', 'United States of America', 'VIRGINIA', 'VA'),
    ('USA', 'United States of America', 'WASHINGTON', 'WA'),
    ('USA', 'United States of America', 'WEST VIRGINIA', 'WV'),
    ('USA', 'United States of America', 'WISCONSIN', 'WI'),
    ('USA', 'United States of America', 'WYOMING', 'WY');

--Insert Canada data
INSERT INTO countries (Country_code, Nation, Federal_state, SEC_code)
VALUES
    ('CAN', 'Canada', 'ALBERTA', 'A0'),
    ('CAN', 'Canada', 'BRITISH COLUMBIA', 'A1'),
    ('CAN', 'Canada', 'MANITOBA', 'A2'),
    ('CAN', 'Canada', 'NEW BRUNSWICK', 'A3'),
    ('CAN', 'Canada', 'NEWFOUNDLAND', 'A4'),
    ('CAN', 'Canada', 'NOVA SCOTIA', 'A5'),
    ('CAN', 'Canada', 'ONTARIO', 'A6'),
    ('CAN', 'Canada', 'PRINCE EDWARD ISLAND', 'A7'),
    ('CAN', 'Canada', 'QUEBEC', 'A8'),
    ('CAN', 'Canada', 'SASKATCHEWAN', 'A9'),
    ('CAN', 'Canada', 'YUKON', 'B0'),
    ('CAN', 'Canada', 'Canada (Federal Level)', 'Z4');
