---
database_connection_string: myDB
database_user: root123
database_pw: secret
tasks:
- comment: Helpful comment
  database_connection_string: overWrite DB
  sp500_fields:
  - NYSE
  priority: 1
  include_sources:
  - all
  exclude_sources:
  - ''
- comment: Helpful comment1
  sp500_fields:
  - MARKET_CAP
  - MONTH_TRADING_VOLUME
  priority: 2
  include_sources:
  - all
  exclude_sources:
  - just_a_bit_brocken_API_1.com
- comment: Helpful comment1
  sp500_fields:
  - LOCATION
  priority: 2
  include_sources:
  - just_a_bit_brocken_API_1.com
  exclude_sources:
  - ''
...