database:
  host: "localhost"
  port: 6543
  username: "postgres"
  password: "password"
  database_name: "collector"
application:
  http_client:
    timeout_milliseconds: 1000000
  tasks:
    - comment: Helpful comment
      actions: [Collect]
      sp500_fields:
        - NYSE
      execution_sequence_position: 1
      include_sources:
        - ALL
    - comment: Helpful comment
      actions: [Stage]
      sp500_fields:
        - NYSE
      execution_sequence_position: 2
      include_sources:
        - ALL
    - comment: Helpful comment1
      actions: [Collect]
      sp500_fields:
        - MARKET_CAP
        - MONTH_TRADING_VOLUME 
      execution_sequence_position: 3
      include_sources:
        - POLYGON_GROUPED_DAILY
    - comment: Helpful comment1
      actions: [Collect]
      sp500_fields:
        - MARKET_CAP
        - MONTH_TRADING_VOLUME 
      execution_sequence_position: 4
      include_sources:
        - POLYGON_OPEN_CLOSE
...