database:
  host: "localhost"
  port: 6543
  username: "postgres"
  password: "password"
  database_name: "exampledb"
application:
  tasks:
    - comment: Helpful comment
      actions: [Collect,Stage]
      sp500_fields:
        - NYSE
      priority: 1
      include_sources:
        - all
    - comment: Helpful comment1
      actions: [Collect]
      sp500_fields:
        - MARKET_CAP
        - MONTH_TRADING_VOLUME 
      priority: 2
      include_sources:
        - all
      exclude_sources:
        - just_a_bit_brocken_API_1.com
    - comment: Helpful comment1
      actions: [Collect,Stage]
      sp500_fields:
        - LOCATION
      priority: 2
      include_sources:
        - just_a_bit_brocken_API_1.com
...