database:
  host: "localhost"
  port: 6543
  username: "postgres"
  password: "password"
  database_name: "collector"
application:
  http_client:
    timeout_milliseconds: 1000000
  task_dependencies:
    - name: task_1
      dependencies: [ ]
    - name: task_2
      dependencies: [ ]
    - name: task_3
      dependencies: [ task_1, task_2 ]
  
  
  tasks:
    - name: task_1
      actions: [Collect]
      comment: Helpful comment
      sp500_fields:
        - NYSE
      include_sources:
        - ALL
    - name: task_2
      actions: [Stage]
      comment: Helpful comment
      sp500_fields:
        - NYSE
      include_sources:
        - ALL
    - name: task_3
      actions: [Collect]
      comment: Helpful comment
      sp500_fields:
        - NYSE
      include_sources:
        - ALL
    # - comment: Helpful comment1
    #   actions: [Collect]
    #   sp500_fields:
    #     - MARKET_CAP
    #     - MONTH_TRADING_VOLUME 
    #   priority: 2
    #   include_sources:
    #     - ALL
    #   exclude_sources:
    #     - NYSE_EVENTS
    # - comment: Helpful comment1
    #   actions: [Collect,Stage]
    #   sp500_fields:
    #     - LOCATION
    #   priority: 2
    #   include_sources:
    #     - NYSE_EVENTS
...