database:
  host: "localhost"
  port: 6543
  username: "postgres"
  password: "password"
  database_name: "collector"
application:
  http_client:
    timeout_milliseconds: 1000000
  # Defines tasks eligible for execution.
  # Note: Tasks listed as dependencies of others must also be explicitly included here to be considered.
  # If a task is referenced in a dependency list but not present in this list, it will be ignored.
  task_dependencies:
    - name: task_1
      dependencies: [ ]
    - name: task_2
      dependencies: [ ]
    - name: task_3
      dependencies: [ task_1, task_2 ]
  
  
  tasks:
    - comment: Helpful comment
      actions: [Collect]
      sp500_fields:
        - NYSE
      execution_sequence_position: 1
      include_sources:
        - ALL
    - comment: Helpful comment
      actions: [Stage]
      sp500_fields:
        - NYSE
      priority: 2
      include_sources:
        - ALL
    # - comment: Helpful comment1
    #   actions: [Collect]
    #   sp500_fields:
    #     - MARKET_CAP
    #     - MONTH_TRADING_VOLUME 
    #   priority: 2
    #   include_sources:
    #     - ALL
    #   exclude_sources:
    #     - NYSE_EVENTS
    # - comment: Helpful comment1
    #   actions: [Collect,Stage]
    #   sp500_fields:
    #     - LOCATION
    #   priority: 2
    #   include_sources:
    #     - NYSE_EVENTS
...